site:
  name: Esplai Sant Josep de Girona
  site: 'https://esplaisantjosep.cat'
  base: '/'
  trailingSlash: false

  # googleSiteVerificationId: orcPxI47GSa-cRvY11tUe6iGg2IO_RPvnA1q95iEM3M

# Default SEO metadata
metadata:
  title:
    default: Esplai Sant Josep de Girona
    template: '%s — Esplai Sant Josep de Girona'
  description: "Educant en el lleure cada dissabte de 16h a 18h al casal d'hivern, projecte groc, colònies, campaments i rutes."
  robots:
    index: true
    follow: true
  openGraph:
    site_name: Esplai Sant Josep de Girona
    images:
      - url: '~/assets/images/default.png'
        width: 1200
        height: 628
    type: website
  twitter:
    handle: '@esplaistjosep'
    site: '@esplaistjosep'
    cardType: summary_large_image

i18n:
  language: ca
  textDirection: ltr

apps:
  blog:
    isEnabled: true
    postsPerPage: 6

    post:
      isEnabled: true
      permalink: '/%slug%' # Variables: %slug%, %year%, %month%, %day%, %hour%, %minute%, %second%, %category%
      robots:
        index: true

    list:
      isEnabled: true
      pathname: 'blog' # Blog main path, you can change this to "articles" (/articles)
      robots:
        index: true

    category:
      isEnabled: true
      pathname: 'category' # Category main path /category/some-category, you can change this to "group" (/group/some-category)
      robots:
        index: true

    tag:
      isEnabled: true
      pathname: 'tag' # Tag main path /tag/some-tag, you can change this to "topics" (/topics/some-category)
      robots:
        index: false

    isRelatedPostsEnabled: true
    relatedPostsCount: 4

analytics:
  vendors:
    googleAnalytics:
      id: null # or "G-XXXXXXXXXX"

ui:
  theme: 'light' # Values: "system" | "light" | "dark" | "light:only" | "dark:only"
